[package]
name = "netlib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.174"
reqwest = { version = "0.12.22", features = ["blocking", "gzip", "rustls-tls", "json"] }
serde_json = "1.0.141"
serde = "1.0.219"
